In [1]:
import pandas as pd
from pathlib import Path
from pandasql import sqldf
import sqlite3
import numpy as np
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import matplotlib
import os

In [2]:
db_path = Path(r'C:\Users\Art\Documents\civ5\Civ5DebugDatabase.db')

In [3]:
cnx = sqlite3.connect(db_path)

In [4]:
pd.read_sql_query('select * from features', cnx)

,ID,Type,Description,Civilopedia,Help,ArtDefineTag,StartingLocationWeight,Movement,SeeThrough,Defense,...,AdvancedStartRemoveCost,PortraitIndex,IconAtlas,PassableTechFeature,FreePromotionIfOwned,LocationUnitFreePromotion,SpawnLocationUnitFreePromotion,AdjacentSpawnLocationUnitFreePromotion,PseudoNaturalWonder,ExtraTurnDamage
0,0,FEATURE_ICE,TXT_KEY_FEATURE_ICE,TXT_KEY_FEATURE_ICE_PEDIA,None,ART_DEF_FEATURE_ICE,0,1,0,0,...,0,6,TERRAIN_ATLAS,None,None,None,None,None,0,0
1,1,FEATURE_JUNGLE,TXT_KEY_FEATURE_JUNGLE,TXT_KEY_CIV5_FEATURES_JUNGLE_TEXT,None,ART_DEF_FEATURE_JUNGLE,-10,2,1,25,...,0,7,TERRAIN_ATLAS,None,None,None,PROMOTION_WOODS_WALKER,None,0,0
2,2,FEATURE_MARSH,TXT_KEY_FEATURE_MARSH,TXT_KEY_CIV5_FEATURES_MARSH_TEXT,None,ART_DEF_FEATURE_MARSH,-10,3,0,5,...,0,8,TERRAIN_ATLAS,None,None,None,None,None,0,0
3,3,FEATURE_OASIS,TXT_KEY_FEATURE_OASIS,TXT_KEY_CIV5_FEATURES_OASIS_TEXT,None,ART_DEF_FEATURE_OASIS,0,1,0,5,...,0,0,NEW_TERRAIN_ATLAS_DLC,None,None,None,None,None,0,0
4,4,FEATURE_FLOOD_PLAINS,TXT_KEY_FEATURE_FLOOD_PLAINS,TXT_KEY_CIV5_FEATURES_FLOODPLAINS_TEXT,None,ART_DEF_FEATURE_FLOOD_PLAINS,0,1,0,5,...,0,2,TERRAIN_ATLAS,None,None,None,None,None,0,0
5,5,FEATURE_FOREST,TXT_KEY_FEATURE_FOREST,TXT_KEY_CIV5_FEATURES_FOREST_TEXT,None,ART_DEF_FEATURE_FOREST,0,2,1,25,...,0,3,TERRAIN_ATLAS,None,None,None,PROMOTION_WOODS_WALKER,None,0,0
6,6,FEATURE_FALLOUT,TXT_KEY_FEATURE_FALLOUT,TXT_KEY_FEATURE_FALLOUT_PEDIA,None,ART_DEF_FEATURE_FALLOUT,0,2,0,5,...,0,17,TERRAIN_ATLAS,None,None,None,None,None,0,-10
7,7,FEATURE_CRATER,TXT_KEY_FEATURE_CRATER,TXT_KEY_CIV5_FEATURES_BARRINGER_TEXT,None,ART_DEF_FEATURE_CRATER,0,2,2,10,...,0,2,NW_ATLAS,None,None,None,None,None,0,0
8,8,FEATURE_FUJI,TXT_KEY_FEATURE_MT_FUJI,TXT_KEY_CIV5_FEATURES_FUJI_TEXT,None,ART_DEF_FEATURE_FUJI,0,1,2,0,...,0,3,NW_ATLAS,None,None,None,None,None,0,0
9,9,FEATURE_MESA,TXT_KEY_FEATURE_MESA,TXT_KEY_CIV5_FEATURES_GRANDMESA_TEXT,None,ART_DEF_FEATURE_MESA,0,2,2,10,...,0,7,NW_ATLAS,None,None,None,None,None,0,0
10,10,FEATURE_REEF,TXT_KEY_FEATURE_REEF,TXT_KEY_CIV5_FEATURES_GREATBARRIERREEF_TEXT,None,ART_DEF_FEATURE_REEF,0,2,0,10,...,0,1,NW_ATLAS,None,None,None,None,None,0,0
11,11,FEATURE_VOLCANO,TXT_KEY_FEATURE_VOLCANO,TXT_KEY_CIV5_FEATURES_KRAKATOA_TEXT,None,ART_DEF_FEATURE_VOLCANO,0,1,2,0,...,0,5,NW_ATLAS,None,None,None,None,None,0,0
12,12,FEATURE_GIBRALTAR,TXT_KEY_FEATURE_GIBRALTAR,TXT_KEY_CIV5_FEATURES_GIBRALTER_TEXT,None,ART_DEF_FEATURE_GIBRALTAR,0,1,2,0,...,0,8,NW_ATLAS,None,None,None,None,None,0,0
13,13,FEATURE_GEYSER,TXT_KEY_FEATURE_GEYSER,TXT_KEY_CIV5_FEATURES_OLDFAITHFUL_TEXT,None,ART_DEF_FEATURE_GEYSER,0,2,1,10,...,0,4,NW_ATLAS,None,None,None,None,None,0,0
14,14,FEATURE_FOUNTAIN_YOUTH,TXT_KEY_FEATURE_FOUNTAIN_YOUTH,TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_TEXT,TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_HELP,ART_DEF_FEATURE_FOUNTAIN_YOUTH,0,2,1,10,...,0,1,NW_ATLAS_DLC,None,PROMOTION_EVERLASTING_YOUTH,None,None,None,0,0
15,15,FEATURE_POTOSI,TXT_KEY_FEATURE_POTOSI,TXT_KEY_CIV5_FEATURES_POTOSI_TEXT,None,ART_DEF_FEATURE_POTOSI,0,1,2,0,...,0,2,NW_ATLAS_DLC,None,None,None,None,None,0,0
16,16,FEATURE_EL_DORADO,TXT_KEY_FEATURE_EL_DORADO,TXT_KEY_CIV5_FEATURES_EL_DORADO_TEXT,None,ART_DEF_FEATURE_EL_DORADO,0,2,2,10,...,0,0,NW_ATLAS_DLC,None,None,None,None,None,0,0
17,17,FEATURE_ATOLL,TXT_KEY_FEATURE_ATOLL,TXT_KEY_CIV5_FEATURES_ATOLL_TEXT,None,ART_DEF_FEATURE_ATOLL,0,1,0,0,...,0,1,NEW_TERRAIN_ATLAS_DLC,None,None,None,None,None,0,0
18,18,FEATURE_SRI_PADA,TXT_KEY_FEATURE_SRI_PADA,TXT_KEY_CIV5_FEATURES_SRI_PADA_TEXT,TXT_KEY_CIV5_FEATURES_SRI_PADA_HELP,ART_DEF_FEATURE_SRI_PADA,0,1,2,0,...,0,10,EXPANSION_BW_ATLAS_2,None,PROMOTION_SACRED_STEPS,None,None,None,0,0
19,19,FEATURE_MT_SINAI,TXT_KEY_FEATURE_MT_SINAI,TXT_KEY_CIV5_FEATURES_MT_SINAI_TEXT,None,ART_DEF_FEATURE_MT_SINAI,0,1,2,0,...,0,9,EXPANSION_BW_ATLAS_2,None,None,None,None,None,0,0
20,20,FEATURE_MT_KAILASH,TXT_KEY_FEATURE_MT_KAILASH,TXT_KEY_CIV5_FEATURES_MT_KAILASH_TEXT,None,ART_DEF_FEATURE_MT_KAILASH,0,1,2,0,...,0,8,EXPANSION_BW_ATLAS_2,None,None,None,None,None,0,0
21,21,FEATURE_ULURU,TXT_KEY_FEATURE_ULURU,TXT_KEY_CIV5_FEATURES_ULURU_TEXT,None,ART_DEF_FEATURE_ULURU,0,2,2,10,...,0,11,EXPANSION_BW_ATLAS_2,None,None,None,None,None,0,0
22,22,FEATURE_LAKE_VICTORIA,TXT_KEY_FEATURE_LAKE_VICTORIA,TXT_KEY_CIV5_FEATURES_LAKE_VICTORIA_TEXT,None,ART_DEF_FEATURE_LAKE_VICTORIA,0,1,0,0,...,0,3,EXPANSION2_WONDER_ATLAS,None,None,None,None,None,0,0
23,23,FEATURE_KILIMANJARO,TXT_KEY_FEATURE_KILIMANJARO,TXT_KEY_CIV5_FEATURES_KILIMANJARO_TEXT,TXT_KEY_CIV5_FEATURES_KILIMANJARO_HELP,ART_DEF_FEATURE_KILIMANJARO,0,1,2,0,...,0,4,EXPANSION2_WONDER_ATLAS,None,PROMOTION_ALTITUDE_TRAINING,None,None,None,0,0
24,24,FEATURE_SOLOMONS_MINES,TXT_KEY_FEATURE_SOLOMONS_MINES,TXT_KEY_CIV5_FEATURES_SOLOMONS_MINES_TEXT,None,ART_DEF_FEATURE_SOLOMONS_MINES,0,2,0,10,...,0,2,EXPANSION2_WONDER_ATLAS,None,None,None,None,None,0,0

In [5]:
CIV_TAG_TO_TEXT_MAP = {
    "CIVILIZATION_AMERICA": "America",
    "CIVILIZATION_ARABIA": "Arabia",
    "CIVILIZATION_AZTEC": "The Aztecs",
    "CIVILIZATION_CHINA": "China",
    "CIVILIZATION_EGYPT": "Egypt",
    "CIVILIZATION_ENGLAND": "England",
    "CIVILIZATION_FRANCE": "France",
    "CIVILIZATION_GERMANY": "Germany",
    "CIVILIZATION_GREECE": "Greece",
    "CIVILIZATION_INDIA": "India",
    "CIVILIZATION_IROQUOIS": "The Iroquois",
    "CIVILIZATION_JAPAN": "Japan",
    "CIVILIZATION_OTTOMAN": "The Ottomans",
    "CIVILIZATION_PERSIA": "Persia",
    "CIVILIZATION_ROME": "Rome",
    "CIVILIZATION_RUSSIA": "Russia",
    "CIVILIZATION_SIAM": "Siam",
    "CIVILIZATION_SONGHAI": "Songhai",
    "CIVILIZATION_MINOR": "City State",
    "CIVILIZATION_BARBARIAN": "Barbarians",
    "CIVILIZATION_MONGOL": "Mongolia",
    "CIVILIZATION_INCA": "The Inca",
    "CIVILIZATION_SPAIN": "Spain",
    "CIVILIZATION_POLYNESIA": "Polynesia",
    "CIVILIZATION_DENMARK": "Denmark",
    "CIVILIZATION_KOREA": "Korea",
    "CIVILIZATION_BABYLON": "Babylon",
    "CIVILIZATION_AUSTRIA": "Austria",
    "CIVILIZATION_BYZANTIUM": "Byzantium",
    "CIVILIZATION_CARTHAGE": "Carthage",
    "CIVILIZATION_CELTS": "The Celts",
    "CIVILIZATION_ETHIOPIA": "Ethiopia",
    "CIVILIZATION_HUNS": "The Huns",
    "CIVILIZATION_MAYA": "The Maya",
    "CIVILIZATION_NETHERLANDS": "The Netherlands",
    "CIVILIZATION_SWEDEN": "Sweden",
    "CIVILIZATION_ASSYRIA": "Assyria",
    "CIVILIZATION_BRAZIL": "Brazil",
    "CIVILIZATION_INDONESIA": "Indonesia",
    "CIVILIZATION_MOROCCO": "Morocco",
    "CIVILIZATION_POLAND": "Poland",
    "CIVILIZATION_PORTUGAL": "Portugal",
    "CIVILIZATION_SHOSHONE": "The Shoshone",
    "CIVILIZATION_VENICE": "Venice",
    "CIVILIZATION_ZULU": "The Zulus"
}

In [6]:
civ_flavors_df = pd.read_sql_query('''
SELECT
    CivilizationType,
    FlavorType,
    Flavor
FROM Leader_Flavors, Civilization_Leaders
WHERE Leader_Flavors.LeaderType = Civilization_Leaders.LeaderheadType
AND CivilizationType != "CIVILIZATION_MINOR"
AND CivilizationType != "CIVILIZATION_BARBARIAN"

UNION

SELECT
    CivilizationType,
    MajorCivApproachType AS FlavorType,
    Bias AS Flavor
FROM Leader_MajorCivApproachBiases, Civilization_Leaders
WHERE Leader_MajorCivApproachBiases.LeaderType = Civilization_Leaders.LeaderheadType
AND CivilizationType != "CIVILIZATION_MINOR"
AND CivilizationType != "CIVILIZATION_BARBARIAN"
''', cnx)

civ_flavors_df['civ'] = civ_flavors_df['CivilizationType'].map(CIV_TAG_TO_TEXT_MAP)
civ_flavors_df = sqldf('''
SELECT
  civ,
  FlavorType,
  Flavor
FROM civ_flavors_df
GROUP BY civ, FlavorType
''')
civ_flavors_df

          civ                   FlavorType  Flavor
0     America                   FLAVOR_AIR       5
1     America               FLAVOR_AIRLIFT       5
2     America           FLAVOR_AIR_CARRIER       5
3     America               FLAVOR_ANTIAIR       7
4     America           FLAVOR_ARCHAEOLOGY       9
...       ...                          ...     ...
1930   Venice  MAJOR_CIV_APPROACH_FRIENDLY       8
1931   Venice   MAJOR_CIV_APPROACH_GUARDED       5
1932   Venice   MAJOR_CIV_APPROACH_HOSTILE       3
1933   Venice   MAJOR_CIV_APPROACH_NEUTRAL       5
1934   Venice       MAJOR_CIV_APPROACH_WAR       2

[1935 rows x 3 columns]

In [7]:
leader_personality_df = pd.read_sql_query('''
SELECT
    Type,
    CivilizationType,
    Description,
    Personality,
    PrimaryVictoryPursuit,
    SecondaryVictoryPursuit
FROM Leaders, Civilization_Leaders
WHERE Leaders.Type = Civilization_Leaders.LeaderheadType
AND CivilizationType != "CIVILIZATION_MINOR"
AND CivilizationType != "CIVILIZATION_BARBARIAN"
''', cnx)

leader_personality_df['civ'] = leader_personality_df['CivilizationType'].map(CIV_TAG_TO_TEXT_MAP)
leader_personality_df['Personality'] = leader_personality_df['Personality'].str.replace('PERSONALITY_', '')
leader_personality_df['PrimaryVictoryPursuit'] = leader_personality_df['PrimaryVictoryPursuit'].str.replace('VICTORY_PURSUIT_', '')
leader_personality_df['SecondaryVictoryPursuit'] = leader_personality_df['SecondaryVictoryPursuit'].str.replace('VICTORY_PURSUIT_', '')
leader_personality_df

,Type,CivilizationType,Description,Personality,PrimaryVictoryPursuit,SecondaryVictoryPursuit,civ
0,LEADER_WASHINGTON,CIVILIZATION_AMERICA,TXT_KEY_LEADER_WASHINGTON,COALITION,None,None,America
1,LEADER_HARUN_AL_RASHID,CIVILIZATION_ARABIA,TXT_KEY_LEADER_HARUN,COALITION,CULTURE,None,Arabia
2,LEADER_MONTEZUMA,CIVILIZATION_AZTEC,TXT_KEY_LEADER_MONTEZUMA,CONQUEROR,DOMINATION,None,The Aztecs
3,LEADER_WU_ZETIAN,CIVILIZATION_CHINA,TXT_KEY_LEADER_WU_ZETIAN,EXPANSIONIST,SCIENCE,DOMINATION,China
4,LEADER_RAMESSES,CIVILIZATION_EGYPT,TXT_KEY_LEADER_RAMESSES,COALITION,CULTURE,None,Egypt
5,LEADER_ELIZABETH,CIVILIZATION_ENGLAND,TXT_KEY_LEADER_ELIZABETH,COALITION,DOMINATION,SCIENCE,England
6,LEADER_NAPOLEON,CIVILIZATION_FRANCE,TXT_KEY_LEADER_NAPOLEON,CONQUEROR,DOMINATION,CULTURE,France
7,LEADER_BISMARCK,CIVILIZATION_GERMANY,TXT_KEY_LEADER_BISMARCK,DIPLOMAT,DIPLOMACY,None,Germany
8,LEADER_ALEXANDER,CIVILIZATION_GREECE,TXT_KEY_LEADER_ALEXANDER,EXPANSIONIST,DIPLOMACY,DOMINATION,Greece
9,LEADER_GANDHI,CIVILIZATION_INDIA,TXT_KEY_LEADER_GANDHI,DIPLOMAT,SCIENCE,CULTURE,India
10,LEADER_HIAWATHA,CIVILIZATION_IROQUOIS,TXT_KEY_LEADER_HIAWATHA,EXPANSIONIST,DOMINATION,DIPLOMACY,The Iroquois
11,LEADER_ODA_NOBUNAGA,CIVILIZATION_JAPAN,TXT_KEY_LEADER_ODA_NOBUNAGA,CONQUEROR,DOMINATION,CULTURE,Japan
12,LEADER_SULEIMAN,CIVILIZATION_OTTOMAN,TXT_KEY_LEADER_SULEIMAN,EXPANSIONIST,SCIENCE,DOMINATION,The Ottomans
13,LEADER_DARIUS,CIVILIZATION_PERSIA,TXT_KEY_LEADER_DARIUS,CONQUEROR,DOMINATION,None,Persia
14,LEADER_AUGUSTUS,CIVILIZATION_ROME,TXT_KEY_LEADER_AUGUSTUS,CONQUEROR,DOMINATION,None,Rome
15,LEADER_CATHERINE,CIVILIZATION_RUSSIA,TXT_KEY_LEADER_CATHERINE,EXPANSIONIST,DOMINATION,SCIENCE,Russia
16,LEADER_RAMKHAMHAENG,CIVILIZATION_SIAM,TXT_KEY_LEADER_RAMKHAMHAENG,DIPLOMAT,DIPLOMACY,None,Siam
17,LEADER_ASKIA,CIVILIZATION_SONGHAI,TXT_KEY_LEADER_ASKIA,CONQUEROR,DOMINATION,None,Songhai
18,LEADER_GENGHIS_KHAN,CIVILIZATION_MONGOL,TXT_KEY_LEADER_GENGHIS_KHAN,CONQUEROR,DOMINATION,None,Mongolia
19,LEADER_PACHACUTI,CIVILIZATION_INCA,TXT_KEY_LEADER_PACHACUTI,EXPANSIONIST,SCIENCE,None,The Inca
20,LEADER_KAMEHAMEHA,CIVILIZATION_POLYNESIA,TXT_KEY_LEADER_KAMEHAMEHA,COALITION,CULTURE,None,Polynesia
21,LEADER_HARALD,CIVILIZATION_DENMARK,TXT_KEY_LEADER_HARALD,CONQUEROR,DOMINATION,None,Denmark
22,LEADER_SEJONG,CIVILIZATION_KOREA,TXT_KEY_LEADER_SEJONG,DIPLOMAT,SCIENCE,None,Korea
23,LEADER_NEBUCHADNEZZAR,CIVILIZATION_BABYLON,TXT_KEY_LEADER_NEBUCHADNEZZAR,COALITION,SCIENCE,None,Babylon
24,LEADER_MARIA,CIVILIZATION_AUSTRIA,TXT_KEY_LEADER_MARIA,DIPLOMAT,DIPLOMACY,CULTURE,Austria
25,LEADER_THEODORA,CIVILIZATION_BYZANTIUM,TXT_KEY_LEADER_THEODORA,DIPLOMAT,None,None,Byzantium
26,LEADER_DIDO,CIVILIZATION_CARTHAGE,TXT_KEY_LEADER_DIDO,EXPANSIONIST,DIPLOMACY,DOMINATION,Carthage
27,LEADER_BOUDICCA,CIVILIZATION_CELTS,TXT_KEY_LEADER_BOUDICCA,EXPANSIONIST,None,None,The Celts
28,LEADER_ATTILA,CIVILIZATION_HUNS,TXT_KEY_LEADER_ATTILA,CONQUEROR,DOMINATION,None,The Huns
29,LEADER_PACAL,CIVILIZATION_MAYA,TXT_KEY_LEADER_PACAL,COALITION,SCIENCE,CULTURE,The Maya
30,LEADER_WILLIAM,CIVILIZATION_NETHERLANDS,TXT_KEY_LEADER_WILLIAM,DIPLOMAT,DIPLOMACY,None,The Netherlands
31,LEADER_GUSTAVUS_ADOLPHUS,CIVILIZATION_SWEDEN,TXT_KEY_LEADER_GUSTAVUS_ADOLPHUS,CONQUEROR,DOMINATION,None,Sweden
32,LEADER_ISABELLA,CIVILIZATION_SPAIN,TXT_KEY_LEADER_ISABELLA,EXPANSIONIST,DOMINATION,DOMINATION,Spain
33,LEADER_SELASSIE,CIVILIZATION_ETHIOPIA,TXT_KEY_LEADER_SELASSIE,COALITION,CULTURE,SCIENCE,Ethiopia
34,LEADER_ASHURBANIPAL,CIVILIZATION_ASSYRIA,TXT_KEY_LEADER_ASHURBANIPAL,CONQUEROR,SCIENCE,DOMINATION,Assyria
35,LEADER_PEDRO,CIVILIZATION_BRAZIL,TXT_KEY_LEADER_PEDRO,DIPLOMAT,CULTURE,None,Brazil
36,LEADER_GAJAH_MADA,CIVILIZATION_INDONESIA,TXT_KEY_LEADER_GAJAH_MADA,EXPANSIONIST,DOMINATION,DIPLOMACY,Indonesia
37,LEADER_AHMAD_ALMANSUR,CIVILIZATION_MOROCCO,TXT_KEY_LEADER_AHMAD_ALMANSUR,DIPLOMAT,DIPLOMACY,CULTURE,Morocco
38,LEADER_CASIMIR,CIVILIZATION_POLAND,TXT_KEY_LEADER_CASIMIR,COALITION,None,None,Poland
39,LEADER_MARIA_I,CIVILIZATION_PORTUGAL,TXT_KEY_LEADER_MARIA_I,DIPLOMAT,DIPLOMACY,None,Portugal
40,LEADER_POCATELLO,CIVILIZATION_SHOSHONE,TXT_KEY_LEADER_POCATELLO,EXPANSIONIST,None,None,The Shoshone
41,LEADER_ENRICO_DANDOLO,CIVILIZATION_VENICE,TXT_KEY_LEADER_ENRICO_DANDOLO,DIPLOMAT,DIPLOMACY,None,Venice
42,LEADER_SHAKA,CIVILIZATION_ZULU,TXT_KEY_LEADER_SHAKA,CONQUEROR,DOMINATION,None,The Zulus

In [8]:
pd.pivot_table(civ_flavors_df, index=['civ'], columns=['FlavorType'], values='Flavor').merge(
    leader_personality_df,
    on='civ',
    how='left'
).to_csv('civ_flavors.csv')

In [9]:
# pd.pivot_table(civ_flavors_df, index=['civ'], columns=['FlavorType'], values='Flavor').to_csv('civ_flavors.csv')

In [10]:
civ_colors_df = pd.read_sql_query('''
SELECT
    Civilizations.Type,
    Colors.Red * 255 AS red,
    Colors.Green * 255 AS green,
    Colors.Blue * 255 AS blue
FROM
    Civilizations, PlayerColors, Colors
WHERE
    Civilizations.DefaultPlayerColor = PlayerColors.Type AND
    PlayerColors.PrimaryColor = Colors.Type
''', cnx)


civ_colors_df['civ'] = civ_colors_df['Type'].map(CIV_TAG_TO_TEXT_MAP)
civ_colors_df = civ_colors_df.drop(columns=['Type']).round()
civ_colors_df

      red  green   blue              civ
0   255.0  255.0  255.0          America
1   146.0  221.0   10.0           Arabia
2   137.0  239.0  213.0       The Aztecs
3   255.0  255.0  255.0            China
4    83.0    0.0  208.0            Egypt
5   255.0  255.0  255.0          England
6   235.0  235.0  139.0           France
7    37.0   43.0   33.0          Germany
8    65.0  141.0  254.0           Greece
9   255.0  153.0   50.0            India
10  252.0  202.0  129.0     The Iroquois
11  184.0    0.0    0.0            Japan
12   18.0   82.0   30.0     The Ottomans
13  245.0  230.0   55.0           Persia
14  240.0  199.0    0.0             Rome
15    0.0    0.0    0.0           Russia
16  177.0    8.0    3.0             Siam
17   90.0    0.0   10.0          Songhai
18    0.0    0.0    0.0       City State
19  184.0    0.0    0.0       Barbarians
20  255.0  120.0    0.0         Mongolia
21    7.0  160.0  119.0         The Inca
22  255.0  168.0  168.0            Spain
23  255.0  255.0   75.0        Polynesia
24  240.0  231.0  180.0          Denmark
25  255.0    0.0    0.0            Korea
26  201.0  248.0  255.0          Babylon
27  255.0  255.0  255.0          Austria
28   61.0    0.0  109.0        Byzantium
29   81.0    0.0  137.0         Carthage
30  148.0  170.0  255.0        The Celts
31  255.0   46.0   46.0         Ethiopia
32   70.0    0.0    4.0         The Huns
33   24.0   63.0   66.0         The Maya
34  255.0  255.0  255.0  The Netherlands
35  249.0  247.0    3.0           Sweden
36  255.0  169.0   13.0          Assyria
37   42.0   84.0   45.0           Brazil
38  159.0   47.0   29.0        Indonesia
39   40.0  179.0   80.0          Morocco
40   57.0    0.0    0.0           Poland
41    4.0   20.0  125.0         Portugal
42   25.0  240.0  206.0     The Shoshone
43  255.0  254.0  216.0           Venice
44  107.0   50.0   25.0        The Zulus

In [11]:
civ_colors_df.to_csv('civ_colors.csv')

In [12]:
civ_bg_colors_df = pd.read_sql_query('''
SELECT
    Civilizations.Type,
    Colors.Red * 255 AS red,
    Colors.Green * 255 AS green,
    Colors.Blue * 255 AS blue
FROM
    Civilizations, PlayerColors, Colors
WHERE
    Civilizations.DefaultPlayerColor = PlayerColors.Type AND
    PlayerColors.SecondaryColor = Colors.Type
''', cnx)


civ_bg_colors_df['civ'] = civ_bg_colors_df['Type'].map(CIV_TAG_TO_TEXT_MAP)
civ_bg_colors_df = civ_bg_colors_df.drop(columns=['Type'])
civ_bg_colors_df

         red     green       blue              civ
0    31.1100   51.0000  120.10500          America
1    43.0950   87.9750   45.90000           Arabia
2   161.4150   57.1200   34.93500       The Aztecs
3     0.0000  148.9200   82.11000            China
4   255.0000  251.9400    3.06000            Egypt
5   108.8850    2.0400    0.00000          England
6    65.0250  141.0150  253.98000           France
7   179.0100  177.9900  184.11000          Germany
8   255.0000  255.0000  255.00000           Greece
9    18.1050  135.9150    6.88500            India
10   65.0250   86.9550   86.95500     The Iroquois
11  255.0000  255.0000  255.00000            Japan
12  247.0950  248.8800  199.92000     The Ottomans
13  176.9700    7.9050    3.06000           Persia
14   70.1250    0.0000  118.06500             Rome
15  238.9350  180.0300    0.00000           Russia
16  245.0550  230.0100   55.08000             Siam
17  213.9450  145.0950   19.12500          Songhai
18  229.5000  229.5000  229.50000       City State
19    0.0000    0.0000    0.00000       Barbarians
20   81.0900    0.0000    8.92500         Mongolia
21  255.0000  184.8750   33.91500         The Inca
22   83.8950   26.0100   26.01000            Spain
23  217.0050   88.9950    0.00000        Polynesia
24  108.9870   42.9930   20.99925          Denmark
25   26.9790   32.9970   96.00750            Korea
26   43.0950   81.0900   97.92000          Babylon
27  234.9825    0.0000    0.00000          Austria
28  113.9850  161.9760  232.99350        Byzantium
29  204.9945  204.9945  204.99450         Carthage
30   21.9810   91.9785   62.98500        The Celts
31    1.6932   39.8565   14.94300         Ethiopia
32  179.9790  177.9900  163.99050         The Huns
33  197.9820  140.9895   98.99100         The Maya
34  255.0000  143.9985    0.00000  The Netherlands
35    7.9815    7.9815  165.97950           Sweden
36  255.0000  244.0000  174.00000          Assyria
37  150.0000  222.0000   10.00000           Brazil
38  111.0000  211.0000  218.00000        Indonesia
39  145.0000    2.0000    0.00000          Morocco
40  245.0000    5.0000    0.00000           Poland
41  255.0000  255.0000  255.00000         Portugal
42   74.0000   59.0000   46.00000     The Shoshone
43  102.0000   34.0000  162.00000           Venice
44  255.0000  232.0000  214.00000        The Zulus

In [13]:
civ_bg_colors_df.to_csv('civ_bg_colors.csv')

In [14]:
pd.read_sql_query("SELECT * FROM PlayerColors", cnx)

,ID,Type,PrimaryColor,SecondaryColor,TextColor
0,0,PLAYERCOLOR_BLACK,COLOR_PLAYER_BLACK,COLOR_PLAYER_WHITE,COLOR_PLAYER_BLACK_TEXT
1,1,PLAYERCOLOR_BLUE,COLOR_PLAYER_BLUE,COLOR_PLAYER_WHITE,COLOR_PLAYER_BLUE_TEXT
2,2,PLAYERCOLOR_BROWN,COLOR_PLAYER_BROWN,COLOR_PLAYER_DARK_YELLOW,COLOR_PLAYER_BROWN_TEXT
3,3,PLAYERCOLOR_CYAN,COLOR_PLAYER_CYAN,COLOR_PLAYER_BLACK,COLOR_PLAYER_CYAN_TEXT
4,4,PLAYERCOLOR_DARK_BLUE,COLOR_PLAYER_DARK_BLUE,COLOR_PLAYER_YELLOW,COLOR_PLAYER_DARK_BLUE_TEXT
...,...,...,...,...,...
101,101,PLAYERCOLOR_POLAND,COLOR_PLAYER_POLAND_ICON,COLOR_PLAYER_POLAND_BACKGROUND,COLOR_PLAYER_WHITE_TEXT
102,102,PLAYERCOLOR_PORTUGAL,COLOR_PLAYER_PORTUGAL_ICON,COLOR_PLAYER_PORTUGAL_BACKGROUND,COLOR_PLAYER_WHITE_TEXT
103,103,PLAYERCOLOR_SHOSHONE,COLOR_PLAYER_SHOSHONE_ICON,COLOR_PLAYER_SHOSHONE_BACKGROUND,COLOR_PLAYER_WHITE_TEXT
104,104,PLAYERCOLOR_VENICE,COLOR_PLAYER_VENICE_ICON,COLOR_PLAYER_VENICE_BACKGROUND,COLOR_PLAYER_WHITE_TEXT
105,105,PLAYERCOLOR_ZULU,COLOR_PLAYER_ZULU_ICON,COLOR_PLAYER_ZULU_BACKGROUND,COLOR_PLAYER_WHITE_TEXT

In [15]:
pd.read_sql_query("SELECT * FROM Colors", cnx)

,ID,Type,Red,Green,Blue,Alpha
0,0,COLOR_CLEAR,1.000000,1.000000,1.000000,0.00
1,1,COLOR_ALPHA_GREY,0.100000,0.100000,0.100000,0.45
2,2,COLOR_WHITE,1.000000,1.000000,1.000000,1.00
3,3,COLOR_BLACK,0.000000,0.000000,0.000000,1.00
4,4,COLOR_DARK_GREY,0.250000,0.250000,0.250000,1.00
...,...,...,...,...,...,...
215,217,COLOR_PLAYER_SHOSHONE_BACKGROUND,0.290196,0.231373,0.180392,1.00
216,218,COLOR_PLAYER_VENICE_ICON,1.000000,0.996078,0.847059,1.00
217,219,COLOR_PLAYER_VENICE_BACKGROUND,0.400000,0.133333,0.635294,1.00
218,220,COLOR_PLAYER_ZULU_ICON,0.419608,0.196078,0.098039,1.00
219,221,COLOR_PLAYER_ZULU_BACKGROUND,1.000000,0.909804,0.839216,1.00

In [16]:
pd.read_sql_query("SELECT * FROM Civilizations", cnx)

,ID,Type,Description,Civilopedia,CivilopediaTag,Strategy,Playable,AIPlayable,ShortDescription,Adjective,...,DerivativeCiv,PortraitIndex,IconAtlas,AlphaIconAtlas,MapImage,DawnOfManQuote,DawnOfManImage,DawnOfManAudio,PackageID,SoundtrackTag
0,0,CIVILIZATION_AMERICA,TXT_KEY_CIV_AMERICA_DESC,None,TXT_KEY_CIV5_UNITEDSTATES,None,1,1,TXT_KEY_CIV_AMERICA_SHORT_DESC,TXT_KEY_CIV_AMERICA_ADJECTIVE,...,None,0,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapAmerica512.dds,TXT_KEY_CIV5_DAWN_UNITEDSTATES_TEXT,DOM_Washington.dds,AS2D_DOM_SPEECH_UNITED_STATES,None,None
1,1,CIVILIZATION_ARABIA,TXT_KEY_CIV_ARABIA_DESC,None,TXT_KEY_CIV5_ARABIA,None,1,1,TXT_KEY_CIV_ARABIA_SHORT_DESC,TXT_KEY_CIV_ARABIA_ADJECTIVE,...,None,1,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapAbbasid512.dds,TXT_KEY_CIV5_DAWN_ARABIA_TEXT,DOM_AlRashid.dds,AS2D_DOM_SPEECH_ARABIA,None,None
2,2,CIVILIZATION_AZTEC,TXT_KEY_CIV_AZTEC_DESC,None,TXT_KEY_CIV5_AZTECS,None,1,1,TXT_KEY_CIV_AZTEC_SHORT_DESC,TXT_KEY_CIV_AZTEC_ADJECTIVE,...,None,2,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapAztec512.dds,TXT_KEY_CIV5_DAWN_AZTECS_TEXT,DOM_Monty.dds,AS2D_DOM_SPEECH_AZTEC,None,None
3,3,CIVILIZATION_CHINA,TXT_KEY_CIV_CHINA_DESC,None,TXT_KEY_CIV5_CHINA,None,1,1,TXT_KEY_CIV_CHINA_SHORT_DESC,TXT_KEY_CIV_CHINA_ADJECTIVE,...,None,4,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapChina512.dds,TXT_KEY_CIV5_DAWN_CHINA_TEXT,DOM_Wu.dds,AS2D_DOM_SPEECH_CHINA,None,None
4,4,CIVILIZATION_EGYPT,TXT_KEY_CIV_EGYPT_DESC,None,TXT_KEY_CIV5_EGYPT,None,1,1,TXT_KEY_CIV_EGYPT_SHORT_DESC,TXT_KEY_CIV_EGYPT_ADJECTIVE,...,None,5,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapEgypt512.dds,TXT_KEY_CIV5_DAWN_EGYPT_TEXT,DOM_Ramesess.dds,AS2D_DOM_SPEECH_EGYPT,None,None
5,5,CIVILIZATION_ENGLAND,TXT_KEY_CIV_ENGLAND_DESC,None,TXT_KEY_CIV5_ENGLAND,None,1,1,TXT_KEY_CIV_ENGLAND_SHORT_DESC,TXT_KEY_CIV_ENGLAND_ADJECTIVE,...,None,6,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapEngland512.dds,TXT_KEY_CIV5_DAWN_ENGLAND_TEXT,DOM_Elizabeth.dds,AS2D_DOM_SPEECH_ENGLAND,None,None
6,6,CIVILIZATION_FRANCE,TXT_KEY_CIV_FRANCE_DESC,None,TXT_KEY_CIV5_FRANCE,None,1,1,TXT_KEY_CIV_FRANCE_SHORT_DESC,TXT_KEY_CIV_FRANCE_ADJECTIVE,...,None,7,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapFrance512.dds,TXT_KEY_CIV5_DAWN_FRANCE_TEXT,DOM_Napoleon.dds,AS2D_DOM_SPEECH_FRANCE,None,None
7,7,CIVILIZATION_GERMANY,TXT_KEY_CIV_GERMANY_DESC,None,TXT_KEY_CIV5_GERMANY,None,1,1,TXT_KEY_CIV_GERMANY_SHORT_DESC,TXT_KEY_CIV_GERMANY_ADJECTIVE,...,None,8,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapGermany512.dds,TXT_KEY_CIV5_DAWN_GERMANY_TEXT,DOM_Bizmark.dds,AS2D_DOM_SPEECH_GERMANY,None,None
8,8,CIVILIZATION_GREECE,TXT_KEY_CIV_GREECE_DESC,None,TXT_KEY_CIV5_GREECE,None,1,1,TXT_KEY_CIV_GREECE_SHORT_DESC,TXT_KEY_CIV_GREECE_ADJECTIVE,...,None,9,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapMacedonia512.dds,TXT_KEY_CIV5_DAWN_GREECE_TEXT,DOM_Alex.dds,AS2D_DOM_SPEECH_GREECE,None,None
9,9,CIVILIZATION_INDIA,TXT_KEY_CIV_INDIA_DESC,None,TXT_KEY_CIV5_INDIA,None,1,1,TXT_KEY_CIV_INDIA_SHORT_DESC,TXT_KEY_CIV_INDIA_ADJECTIVE,...,None,11,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapIndia512.dds,TXT_KEY_CIV5_DAWN_INDIA_TEXT,DOM_Gandhi.dds,AS2D_DOM_SPEECH_INDIA,None,None
10,10,CIVILIZATION_IROQUOIS,TXT_KEY_CIV_IROQUOIS_DESC,None,TXT_KEY_CIV5_IROQUOIS,None,1,1,TXT_KEY_CIV_IROQUOIS_SHORT_DESC,TXT_KEY_CIV_IROQUOIS_ADJECTIVE,...,None,12,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapIroquoi512.dds,TXT_KEY_CIV5_DAWN_IROQUOIS_TEXT,DOM_Hiawatha.dds,AS2D_DOM_SPEECH_IROQUOIS,None,None
11,11,CIVILIZATION_JAPAN,TXT_KEY_CIV_JAPAN_DESC,None,TXT_KEY_CIV5_JAPAN,None,1,1,TXT_KEY_CIV_JAPAN_SHORT_DESC,TXT_KEY_CIV_JAPAN_ADJECTIVE,...,None,13,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapJapan512.dds,TXT_KEY_CIV5_DAWN_JAPAN_TEXT,DOM_Oda.dds,AS2D_DOM_SPEECH_JAPAN,None,None
12,12,CIVILIZATION_OTTOMAN,TXT_KEY_CIV_OTTOMAN_DESC,None,TXT_KEY_CIV5_OTTOMAN,None,1,1,TXT_KEY_CIV_OTTOMAN_SHORT_DESC,TXT_KEY_CIV_OTTOMAN_ADJECTIVE,...,None,15,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapOttoman512.dds,TXT_KEY_CIV5_DAWN_OTTOMANS_TEXT,DOM_Suleiman.dds,AS2D_DOM_SPEECH_OTTOMANS,None,None
13,13,CIVILIZATION_PERSIA,TXT_KEY_CIV_PERSIA_DESC,None,TXT_KEY_CIV5_PERSIA,None,1,1,TXT_KEY_CIV_PERSIA_SHORT_DESC,TXT_KEY_CIV_PERSIA_ADJECTIVE,...,None,16,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapPersia512.dds,TXT_KEY_CIV5_DAWN_PERSIA_TEXT,DOM_Darius.dds,AS2D_DOM_SPEECH_PERSIA,None,None
14,14,CIVILIZATION_ROME,TXT_KEY_CIV_ROME_DESC,None,TXT_KEY_CIV5_ROME,None,1,1,TXT_KEY_CIV_ROME_SHORT_DESC,TXT_KEY_CIV_ROME_ADJECTIVE,...,None,17,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapRome512.dds,TXT_KEY_CIV5_DAWN_ROME_TEXT,DOM_Augustus.dds,AS2D_DOM_SPEECH_ROME,None,None
15,15,CIVILIZATION_RUSSIA,TXT_KEY_CIV_RUSSIA_DESC,None,TXT_KEY_CIV5_RUSSIA,None,1,1,TXT_KEY_CIV_RUSSIA_SHORT_DESC,TXT_KEY_CIV_RUSSIA_ADJECTIVE,...,None,18,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapRussia512.dds,TXT_KEY_CIV5_DAWN_RUSSIA_TEXT,DOM_Catherine.dds,AS2D_DOM_SPEECH_RUSSIA,None,None
16,16,CIVILIZATION_SIAM,TXT_KEY_CIV_SIAM_DESC,None,TXT_KEY_CIV5_SIAM,None,1,1,TXT_KEY_CIV_SIAM_SHORT_DESC,TXT_KEY_CIV_SIAM_ADJECTIVE,...,None,19,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapSiam512.dds,TXT_KEY_CIV5_DAWN_SIAM_TEXT,DOM_Ramkamhaeng.dds,AS2D_DOM_SPEECH_SIAM,None,None
17,17,CIVILIZATION_SONGHAI,TXT_KEY_CIV_SONGHAI_DESC,None,TXT_KEY_CIV5_SONGHAI,None,1,1,TXT_KEY_CIV_SONGHAI_SHORT_DESC,TXT_KEY_CIV_SONGHAI_ADJECTIVE,...,None,20,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,MapSonghai512.dds,TXT_KEY_CIV5_DAWN_SONGHAI_TEXT,DOM_Askia.dds,AS2D_DOM_SPEECH_SONGIA,None,None
18,18,CIVILIZATION_MINOR,TXT_KEY_CIV_MINOR_DESC,None,None,None,0,0,TXT_KEY_CIV_MINOR_SHORT_DESC,TXT_KEY_CIV_MINOR_ADJECTIVE,...,None,22,CIV_COLOR_ATLAS,CIV_ALPHA_ATLAS,None,None,None,None,None,None
19,19,CIVILIZATION_BARBARIAN,TXT_KEY_CIV_BARBARIAN_DESC,None,None,None,0,0,TXT_KEY_CIV_BARBARIAN_SHORT_DESC,TXT_KEY_CIV_BARBARIAN_ADJECTIVE,...,None,0,SHARED_CIV_COLOR_ATLAS,SHARED_CIV_ALPHA_ATLAS,None,None,None,None,None,None
20,20,CIVILIZATION_MONGOL,TXT_KEY_CIV_MONGOL_DESC,None,TXT_KEY_CIV5_MONGOLIA,None,1,1,TXT_KEY_CIV_MONGOL_SHORT_DESC,TXT_KEY_CIV_MONGOL_ADJECTIVE,...,None,0,GENGHIS_CIV_COLOR_ATLAS,GENGHIS_CIV_ALPHA_ATLAS,MapMongolia360x410.dds,TXT_KEY_CIV5_DAWN_MONGOLIA_TEXT,DOM_Genghis.dds,AS2D_DOM_SPEECH_MONGOL,293C1EE3117644F6AC1F59663826DE74,None
21,21,CIVILIZATION_INCA,TXT_KEY_CIV_INCA_DESC,None,TXT_KEY_CIV5_INCA,None,1,1,TXT_KEY_CIV_INCA_SHORT_DESC,TXT_KEY_CIV_INCA_ADJECTIVE,...,None,0,PACHACUTI_CIV_COLOR_ATLAS,PACHACUTI_CIV_ALPHA_ATLAS,MapInca360x410.dds,TXT_KEY_CIV5_DAWN_INCA_TEXT,DOM_Pachacuti.dds,AS2D_DOM_SPEECH_INCA,B685D5DE7CCA4E7581B42F60754E6330,None
22,22,CIVILIZATION_SPAIN,TXT_KEY_CIV_SPAIN_DESC,None,TXT_KEY_CIV5_SPAIN,None,1,1,TXT_KEY_CIV_SPAIN_SHORT_DESC,TXT_KEY_CIV_SPAIN_ADJECTIVE,...,None,1,ISABELLA_CIV_COLOR_ATLAS,ISABELLA_CIV_ALPHA_ATLAS,MapSpain360x410.dds,TXT_KEY_CIV5_DAWN_SPAIN_TEXT,DOM_Isabella.dds,AS2D_DOM_SPEECH_SPAIN,B685D5DE7CCA4E7581B42F60754E6330,None
23,23,CIVILIZATION_POLYNESIA,TXT_KEY_CIV_POLYNESIA_DESC,None,TXT_KEY_CIV5_POLYNESIA,None,1,1,TXT_KEY_CIV_POLYNESIA_SHORT_DESC,TXT_KEY_CIV_POLYNESIA_ADJECTIVE,...,None,0,KAMEHAMEHA_CIV_COLOR_ATLAS,KAMEHAMEHA_CIV_ALPHA_ATLAS,MapPOLYNESIA360x410.dds,TXT_KEY_CIV5_DAWN_POLYNESIA_TEXT,DOM_KAMEHAMEHA.dds,AS2D_DOM_SPEECH_POLYNESIA,ECF7C605BA114CAC8D80D71306AAC471,Aztec
24,24,CIVILIZATION_DENMARK,TXT_KEY_CIV_DENMARK_DESC,None,TXT_KEY_CIV5_DENMARK,None,1,1,TXT_KEY_CIV_DENMARK_SHORT_DESC,TXT_KEY_CIV_DENMARK_ADJECTIVE,...,None,0,HARALD_CIV_COLOR_ATLAS,HARALD_CIV_ALPHA_ATLAS,MapDENMARK360x410.dds,TXT_KEY_CIV5_DAWN_DENMARK_TEXT,DOM_Harald.dds,AS2D_DOM_SPEECH_DENMARK,B3030D39C0D84BC791B17AD1CAF585AB,None
25,25,CIVILIZATION_KOREA,TXT_KEY_CIV_KOREA_DESC,None,TXT_KEY_CIV5_KOREA,None,1,1,TXT_KEY_CIV_KOREA_SHORT_DESC,TXT_KEY_CIV_KOREA_ADJECTIVE,...,None,0,SEJONG_CIV_COLOR_ATLAS,SEJONG_CIV_ALPHA_ATLAS,MapKorea360x410.dds,TXT_KEY_CIV5_DAWN_KOREA_TEXT,DOM_SEJONG.dds,AS2D_DOM_SPEECH_KOREA,112C22B2530842B6B734171CCAB3037B,None
26,26,CIVILIZATION_BABYLON,TXT_KEY_CIV_BABYLON_DESC,None,TXT_KEY_CIV5_BABYLON,None,1,1,TXT_KEY_CIV_BABYLON_SHORT_DESC,TXT_KEY_CIV_BABYLON_ADJECTIVE,...,None,0,NEB_CIV_COLOR_ATLAS,NEB_CIV_ALPHA_ATLAS,MapBabylon512.dds,TXT_KEY_CIV5_DAWN_BABYLON_TEXT,DOM_Nebuchadnezzar.dds,AS2D_DOM_SPEECH_BABYLON,7459BA32576444AE8E9501AD0E0EFD48,None
27,27,CIVILIZATION_AUSTRIA,TXT_KEY_CIV_AUSTRIA_DESC,None,TXT_KEY_CIV5_AUSTRIA,None,1,1,TXT_KEY_CIV_AUSTRIA_SHORT_DESC,TXT_KEY_CIV_AUSTRIA_ADJECTIVE,...,None,0,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapAustria512.dds,TXT_KEY_CIV5_DAWN_AUSTRIA_TEXT,DOM_Maria_Theresa.dds,AS2D_DOM_SPEECH_AUSTRIA,0E3751A1F8404E1B9706519BF484E59D,None
28,28,CIVILIZATION_BYZANTIUM,TXT_KEY_CIV_BYZANTIUM_DESC,None,TXT_KEY_CIV5_BYZANTIUM,None,1,1,TXT_KEY_CIV_BYZANTIUM_SHORT_DESC,TXT_KEY_CIV_BYZANTIUM_ADJECTIVE,...,None,1,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapByzantium512.dds,TXT_KEY_CIV5_DAWN_BYZANTIUM_TEXT,DOM_Theodora.dds,AS2D_DOM_SPEECH_BYZANTIUM,0E3751A1F8404E1B9706519BF484E59D,None
29,29,CIVILIZATION_CARTHAGE,TXT_KEY_CIV_CARTHAGE_DESC,None,TXT_KEY_CIV5_CARTHAGE,None,1,1,TXT_KEY_CIV_CARTHAGE_SHORT_DESC,TXT_KEY_CIV_CARTHAGE_ADJECTIVE,...,None,2,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapCarthage512.dds,TXT_KEY_CIV5_DAWN_CARTHAGE_TEXT,DOM_Dido.dds,AS2D_DOM_SPEECH_CARTHAGE,0E3751A1F8404E1B9706519BF484E59D,None
30,30,CIVILIZATION_CELTS,TXT_KEY_CIV_CELTS_DESC,None,TXT_KEY_CIV5_CELTS,None,1,1,TXT_KEY_CIV_CELTS_SHORT_DESC,TXT_KEY_CIV_CELTS_ADJECTIVE,...,None,3,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapCelts512.dds,TXT_KEY_CIV5_DAWN_CELTS_TEXT,DOM_Boudicca.dds,AS2D_DOM_SPEECH_CELTS,0E3751A1F8404E1B9706519BF484E59D,None
31,31,CIVILIZATION_ETHIOPIA,TXT_KEY_CIV_ETHIOPIA_DESC,None,TXT_KEY_CIV5_ETHIOPIA,None,1,1,TXT_KEY_CIV_ETHIOPIA_SHORT_DESC,TXT_KEY_CIV_ETHIOPIA_ADJECTIVE,...,None,4,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapEthiopia512.dds,TXT_KEY_CIV5_DAWN_ETHIOPIA_TEXT,DOM_Haile_Selassie.dds,AS2D_DOM_SPEECH_ETHIOPIA,0E3751A1F8404E1B9706519BF484E59D,None
32,32,CIVILIZATION_HUNS,TXT_KEY_CIV_HUNS_DESC,None,TXT_KEY_CIV5_HUNS,None,1,1,TXT_KEY_CIV_HUNS_SHORT_DESC,TXT_KEY_CIV_HUNS_ADJECTIVE,...,None,5,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapHuns512.dds,TXT_KEY_CIV5_DAWN_HUNS_TEXT,DOM_Attila.dds,AS2D_DOM_SPEECH_HUNS,0E3751A1F8404E1B9706519BF484E59D,None
33,33,CIVILIZATION_MAYA,TXT_KEY_CIV_MAYA_DESC,None,TXT_KEY_CIV5_MAYA,None,1,1,TXT_KEY_CIV_MAYA_SHORT_DESC,TXT_KEY_CIV_MAYA_ADJECTIVE,...,None,6,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapMaya512.dds,TXT_KEY_CIV5_DAWN_MAYA_TEXT,DOM_Pacal_the_Great.dds,AS2D_DOM_SPEECH_MAYA,0E3751A1F8404E1B9706519BF484E59D,None
34,34,CIVILIZATION_NETHERLANDS,TXT_KEY_CIV_NETHERLANDS_DESC,None,TXT_KEY_CIV5_NETHERLANDS,None,1,1,TXT_KEY_CIV_NETHERLANDS_SHORT_DESC,TXT_KEY_CIV_NETHERLANDS_ADJECTIVE,...,None,7,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapNetherlands512.dds,TXT_KEY_CIV5_DAWN_NETHERLANDS_TEXT,DOM_William_of_Orange.dds,AS2D_DOM_SPEECH_NETHERLANDS,0E3751A1F8404E1B9706519BF484E59D,None
35,35,CIVILIZATION_SWEDEN,TXT_KEY_CIV_SWEDEN_DESC,None,TXT_KEY_CIV5_SWEDEN,None,1,1,TXT_KEY_CIV_SWEDEN_SHORT_DESC,TXT_KEY_CIV_SWEDEN_ADJECTIVE,...,None,8,EXPANSION_CIV_COLOR_ATLAS,EXPANSION_CIV_ALPHA_ATLAS,MapSweden512.dds,TXT_KEY_CIV5_DAWN_SWEDEN_TEXT,DOM_Gustavus_Adolphus.dds,AS2D_DOM_SPEECH_SWEDEN,0E3751A1F8404E1B9706519BF484E59D,None
36,36,CIVILIZATION_ASSYRIA,TXT_KEY_CIV_ASSYRIA_DESC,None,TXT_KEY_CIV5_ASSYRIA,None,1,1,TXT_KEY_CIV_ASSYRIA_SHORT_DESC,TXT_KEY_CIV_ASSYRIA_ADJECTIVE,...,None,0,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapAssyria360x410.dds,TXT_KEY_CIV5_DAWN_ASSYRIA_TEXT,DOM_Ashurbanipal.dds,AS2D_DOM_SPEECH_ASSYRIA,6DA0763641234018B6436575B4EC336B,None
37,37,CIVILIZATION_BRAZIL,TXT_KEY_CIV_BRAZIL_DESC,None,TXT_KEY_CIV5_BRAZIL,None,1,1,TXT_KEY_CIV_BRAZIL_SHORT_DESC,TXT_KEY_CIV_BRAZIL_ADJECTIVE,...,None,1,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapBrazil360x410.dds,TXT_KEY_CIV5_DAWN_BRAZIL_TEXT,DOM_Pedro_II.dds,AS2D_DOM_SPEECH_BRAZIL,6DA0763641234018B6436575B4EC336B,None
38,38,CIVILIZATION_INDONESIA,TXT_KEY_CIV_INDONESIA_DESC,None,TXT_KEY_CIV5_INDONESIA,None,1,1,TXT_KEY_CIV_INDONESIA_SHORT_DESC,TXT_KEY_CIV_INDONESIA_ADJECTIVE,...,None,2,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapIndonesia360x410.dds,TXT_KEY_CIV5_DAWN_INDONESIA_TEXT,DOM_Gajah_Mada.dds,AS2D_DOM_SPEECH_INDONESIA,6DA0763641234018B6436575B4EC336B,None
39,39,CIVILIZATION_MOROCCO,TXT_KEY_CIV_MOROCCO_DESC,None,TXT_KEY_CIV5_MOROCCO,None,1,1,TXT_KEY_CIV_MOROCCO_SHORT_DESC,TXT_KEY_CIV_MOROCCO_ADJECTIVE,...,None,3,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapMorocco360x410.dds,TXT_KEY_CIV5_DAWN_MOROCCO_TEXT,DOM_Ahmed_AlMansur.dds,AS2D_DOM_SPEECH_MOROCCO,6DA0763641234018B6436575B4EC336B,None
40,40,CIVILIZATION_POLAND,TXT_KEY_CIV_POLAND_DESC,None,TXT_KEY_CIV5_POLAND,None,1,1,TXT_KEY_CIV_POLAND_SHORT_DESC,TXT_KEY_CIV_POLAND_ADJECTIVE,...,None,4,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapPoland360x410.dds,TXT_KEY_CIV5_DAWN_POLAND_TEXT,DOM_Casimir.dds,AS2D_DOM_SPEECH_POLAND,6DA0763641234018B6436575B4EC336B,None
41,41,CIVILIZATION_PORTUGAL,TXT_KEY_CIV_PORTUGAL_DESC,None,TXT_KEY_CIV5_PORTUGAL,None,1,1,TXT_KEY_CIV_PORTUGAL_SHORT_DESC,TXT_KEY_CIV_PORTUGAL_ADJECTIVE,...,None,5,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapPortugal360x410.dds,TXT_KEY_CIV5_DAWN_PORTUGAL_TEXT,DOM_Maria_I.dds,AS2D_DOM_SPEECH_PORTUGAL,6DA0763641234018B6436575B4EC336B,None
42,42,CIVILIZATION_SHOSHONE,TXT_KEY_CIV_SHOSHONE_DESC,None,TXT_KEY_CIV5_SHOSHONE,None,1,1,TXT_KEY_CIV_SHOSHONE_SHORT_DESC,TXT_KEY_CIV_SHOSHONE_ADJECTIVE,...,None,6,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapShoshone360x410.dds,TXT_KEY_CIV5_DAWN_SHOSHONE_TEXT,DOM_Pocatello.dds,AS2D_DOM_SPEECH_SHOSHONE,6DA0763641234018B6436575B4EC336B,None
43,43,CIVILIZATION_VENICE,TXT_KEY_CIV_VENICE_DESC,None,TXT_KEY_CIV5_VENICE,None,1,1,TXT_KEY_CIV_VENICE_SHORT_DESC,TXT_KEY_CIV_VENICE_ADJECTIVE,...,None,7,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapVenice360x410.dds,TXT_KEY_CIV5_DAWN_VENICE_TEXT,DOM_Enrico_Dandolo.dds,AS2D_DOM_SPEECH_VENICE,6DA0763641234018B6436575B4EC336B,None
44,44,CIVILIZATION_ZULU,TXT_KEY_CIV_ZULU_DESC,None,TXT_KEY_CIV5_ZULU,None,1,1,TXT_KEY_CIV_ZULU_SHORT_DESC,TXT_KEY_CIV_ZULU_ADJECTIVE,...,None,8,EXPANSION2_CIV_COLOR_ATLAS,EXPANSION2_CIV_ALPHA_ATLAS,MapZulu360x410.dds,TXT_KEY_CIV5_DAWN_ZULU_TEXT,DOM_Shaka.dds,AS2D_DOM_SPEECH_ZULU,6DA0763641234018B6436575B4EC336B,None

In [17]:
pd.read_sql_query("SELECT * FROM Civilizations", cnx).columns

Index(['ID', 'Type', 'Description', 'Civilopedia', 'CivilopediaTag',
       'Strategy', 'Playable', 'AIPlayable', 'ShortDescription', 'Adjective',
       'DefaultPlayerColor', 'ArtDefineTag', 'ArtStyleType', 'ArtStyleSuffix',
       'ArtStylePrefix', 'DerivativeCiv', 'PortraitIndex', 'IconAtlas',
       'AlphaIconAtlas', 'MapImage', 'DawnOfManQuote', 'DawnOfManImage',
       'DawnOfManAudio', 'PackageID', 'SoundtrackTag'],
      dtype='object')

In [18]:
pd.read_sql_query("SELECT * FROM Civilizations", cnx)[['DefaultPlayerColor']]

         DefaultPlayerColor
0       PLAYERCOLOR_AMERICA
1        PLAYERCOLOR_ARABIA
2         PLAYERCOLOR_AZTEC
3         PLAYERCOLOR_CHINA
4         PLAYERCOLOR_EGYPT
5       PLAYERCOLOR_ENGLAND
6        PLAYERCOLOR_FRANCE
7       PLAYERCOLOR_GERMANY
8        PLAYERCOLOR_GREECE
9         PLAYERCOLOR_INDIA
10     PLAYERCOLOR_IROQUOIS
11        PLAYERCOLOR_JAPAN
12      PLAYERCOLOR_OTTOMAN
13       PLAYERCOLOR_PERSIA
14         PLAYERCOLOR_ROME
15       PLAYERCOLOR_RUSSIA
16         PLAYERCOLOR_SIAM
17      PLAYERCOLOR_SONGHAI
18  PLAYERCOLOR_MINOR_WHITE
19    PLAYERCOLOR_BARBARIAN
20       PLAYERCOLOR_MONGOL
21         PLAYERCOLOR_INCA
22        PLAYERCOLOR_SPAIN
23    PLAYERCOLOR_POLYNESIA
24      PLAYERCOLOR_DENMARK
25        PLAYERCOLOR_KOREA
26      PLAYERCOLOR_BABYLON
27      PLAYERCOLOR_AUSTRIA
28    PLAYERCOLOR_BYZANTIUM
29     PLAYERCOLOR_CARTHAGE
30        PLAYERCOLOR_CELTS
31     PLAYERCOLOR_ETHIOPIA
32         PLAYERCOLOR_HUNS
33         PLAYERCOLOR_MAYA
34  PLAYERCOLOR_NETHERLANDS
35       PLAYERCOLOR_SWEDEN
36      PLAYERCOLOR_ASSYRIA
37       PLAYERCOLOR_BRAZIL
38    PLAYERCOLOR_INDONESIA
39      PLAYERCOLOR_MOROCCO
40       PLAYERCOLOR_POLAND
41     PLAYERCOLOR_PORTUGAL
42     PLAYERCOLOR_SHOSHONE
43       PLAYERCOLOR_VENICE
44         PLAYERCOLOR_ZULU